### ISSUE TITLE
未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。

### ISSUE THREAD

**Issue by yazhengwang** [one-pupil/wx-mpvue#1]
1. npm  install 
2. npm run dev 
 报错  未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。

**Comment by yazhengwang** [comment]
![image](https://user-images.githubusercontent.com/14901532/43818024-407fff6a-9b0f-11e8-8128-65129d3a02b5.png)

**Comment by cduyzh** [comment]
一看就是mpvue-loader升级导致

**Comment by yazhengwang** [comment]
@cduyzh 需要怎么解决呢

**Comment by cduyzh** [comment]
降级处理，或者看下我的仓库里的兼容写法，要自己手动改代码实现复制过去。https://github.com/cduyzh/mp_webpack 可以看下这个

**Comment by imondo** [comment]
@yazhengwang 更新了模版，是上面那哥们说的原因，具体可参考他的处理方法，我的模版直接更新了。
